version: "3"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/opt/app
      - /opt/app/node_modules
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./server/src/generated/:/opt/server/src/generated
      - ./web:/opt/app
      - /opt/app/node_modules
